import React, { useState } from 'react';
import { Upload, FileText, Brain, Download, AlertCircle, MessageCircle, Send, Home } from 'lucide-react';
import jsPDF from 'jspdf';

const DocumentAnalyzer = () => {
  const [file, setFile] = useState(null);
  const [analysis, setAnalysis] = useState(null);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [error, setError] = useState('');
  const [chatMessages, setChatMessages] = useState([]);
  const [chatInput, setChatInput] = useState('');
  const [isChatting, setIsChatting] = useState(false);
  const [documentContent, setDocumentContent] = useState('');

  const handleBackToDashboard = () => {
    window.location.href = '/lawyer-dashboard';
  };

  const handleFileSelect = (e) => {
    const selectedFile = e.target.files[0];
    if (selectedFile) {
      const allowedTypes = ['application/pdf', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'text/plain'];
      if (allowedTypes.includes(selectedFile.type)) {
        setFile(selectedFile);
        setError('');
        setAnalysis(null);
      } else {
        setError('Please select a PDF, DOCX, or TXT file');
        setFile(null);
      }
    }
  };

  const analyzeDocument = async () => {
    if (!file) return;

    setIsAnalyzing(true);
    setError('');

    const formData = new FormData();
    formData.append('document', file);

    try {
      const token = localStorage.getItem('token');
      const response = await fetch('/api/ai/summarize-document', {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${token}`
        },
        body: formData
      });

      const data = await response.json();

      if (data.success) {
        setAnalysis({
          summary: data.summary,
          fileName: data.fileName,
          fileType: data.fileType,
          timestamp: new Date()
        });
        setDocumentContent(data.summary); // Store for chat context
        setChatMessages([{
          id: 1,
          text: "Document analyzed! You can now ask me questions about this document. For example: 'What are the main risks?' or 'Explain this contract clause'",
          sender: 'ai',
          timestamp: new Date()
        }]);
      } else {
        throw new Error(data.error || 'Analysis failed');
      }
    } catch (error) {
      setError(error.message || 'Failed to analyze document');
    } finally {
      setIsAnalyzing(false);
    }
  };

  const downloadAnalysis = () => {
    if (!analysis) return;

    const pdf = new jsPDF();
    const pageWidth = pdf.internal.pageSize.getWidth();
    const margin = 20;
    const maxWidth = pageWidth - 2 * margin;
    let yPosition = 30;

    // Header with logo area
    pdf.setFillColor(59, 130, 246); // Blue background
    pdf.rect(0, 0, pageWidth, 40, 'F');
    
    // Title
    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(24);
    pdf.setFont('helvetica', 'bold');
    pdf.text('AI Document Analysis Report', margin, 25);
    
    yPosition = 60;
    
    // Document Info Section
    pdf.setTextColor(0, 0, 0);
    pdf.setFillColor(248, 250, 252); // Light gray background
    pdf.rect(margin, yPosition - 5, maxWidth, 25, 'F');
    
    pdf.setFontSize(14);
    pdf.setFont('helvetica', 'bold');
    pdf.text('Document Information', margin + 5, yPosition + 5);
    
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    pdf.text(`File: ${analysis.fileName}`, margin + 5, yPosition + 12);
    pdf.text(`Type: ${analysis.fileType.toUpperCase()}`, margin + 5, yPosition + 18);
    pdf.text(`Generated: ${analysis.timestamp.toLocaleString()}`, margin + 5, yPosition + 24);
    
    yPosition += 40;
    
    // Analysis Content Section
    pdf.setFontSize(16);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(59, 130, 246);
    pdf.text('Analysis Results', margin, yPosition);
    
    yPosition += 15;
    
    // Content with proper text wrapping
    pdf.setFontSize(11);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(0, 0, 0);
    
    const lines = pdf.splitTextToSize(analysis.summary, maxWidth);
    
    lines.forEach((line) => {
      if (yPosition > pdf.internal.pageSize.getHeight() - 30) {
        pdf.addPage();
        yPosition = 30;
      }
      pdf.text(line, margin, yPosition);
      yPosition += 6;
    });
    
    // Footer
    const pageCount = pdf.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      pdf.setPage(i);
      pdf.setFontSize(8);
      pdf.setTextColor(128, 128, 128);
      pdf.text(
        `Generated by Legal City AI - Page ${i} of ${pageCount}`,
        margin,
        pdf.internal.pageSize.getHeight() - 10
      );
    }
    
    // Save the PDF
    pdf.save(`AI-Analysis-${analysis.fileName}-${Date.now()}.pdf`);
  };

  const sendChatMessage = async () => {
    if (!chatInput.trim() || isChatting) return;

    const userMessage = {
      id: Date.now(),
      text: chatInput,
      sender: 'user',
      timestamp: new Date()
    };

    setChatMessages(prev => [...prev, userMessage]);
    setChatInput('');
    setIsChatting(true);

    try {
      const token = localStorage.getItem('token');
      const response = await fetch('/api/ai/document-chat', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token}`
        },
        body: JSON.stringify({
          message: chatInput,
          documentContext: documentContent
        })
      });

      const data = await response.json();

      if (data.success) {
        const aiMessage = {
          id: Date.now() + 1,
          text: data.response,
          sender: 'ai',
          timestamp: new Date()
        };
        setChatMessages(prev => [...prev, aiMessage]);
      } else {
        throw new Error(data.error || 'Failed to get response');
      }
    } catch (error) {
      const errorMessage = {
        id: Date.now() + 1,
        text: "I'm sorry, I'm having trouble responding right now. Please try again.",
        sender: 'ai',
        timestamp: new Date()
      };
      setChatMessages(prev => [...prev, errorMessage]);
    } finally {
      setIsChatting(false);
    }
  };

  const handleChatKeyPress = (e) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      sendChatMessage();
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-indigo-50">
      <div className="max-w-5xl mx-auto px-6 py-8">
        {/* Header */}
        <div className="mb-10">
          <button 
            onClick={handleBackToDashboard}
            className="flex items-center gap-2 px-4 py-2 text-gray-600 hover:text-blue-600 mb-6 transition-colors rounded-lg hover:bg-white/50"
          >
            <Home className="w-4 h-4" />
            Dashboard Home
          </button>
          <div className="text-center">
            <div className="inline-flex items-center gap-3 mb-4">
              <div className="p-3 bg-gradient-to-r from-blue-500 to-indigo-600 rounded-2xl shadow-lg">
                <Brain className="w-8 h-8 text-white" />
              </div>
              <h1 className="text-4xl font-bold bg-gradient-to-r from-gray-800 to-blue-600 bg-clip-text text-transparent">
                AI Document Analyzer
              </h1>
            </div>
            <p className="text-lg text-gray-600 max-w-2xl mx-auto">
              Transform your legal documents with intelligent AI analysis and insights
            </p>
          </div>
        </div>

        {/* Upload Section */}
        <div className="bg-white rounded-3xl shadow-xl border border-gray-100 p-8 mb-8 hover:shadow-2xl transition-shadow">
          <div className="text-center mb-6">
            <h2 className="text-2xl font-bold text-gray-800 mb-2">Upload Your Document</h2>
            <p className="text-gray-600">Drag and drop or click to select your legal document</p>
          </div>
          
          <div className="relative">
            <div className="border-3 border-dashed border-blue-300 rounded-2xl p-12 text-center hover:border-blue-500 hover:bg-blue-50/50 transition-all duration-300 group">
              <input
                type="file"
                onChange={handleFileSelect}
                accept=".pdf,.docx,.txt"
                className="hidden"
                id="document-upload"
              />
              <label htmlFor="document-upload" className="cursor-pointer">
                <div className="mb-4">
                  <Upload className="mx-auto text-blue-400 group-hover:text-blue-600 transition-colors" size={60} />
                </div>
                <p className="text-xl font-semibold text-gray-700 mb-2">Drop your document here</p>
                <p className="text-gray-500 mb-4">or click to browse files</p>
                <div className="inline-flex items-center gap-2 px-6 py-3 bg-gradient-to-r from-blue-500 to-indigo-600 text-white rounded-xl font-medium hover:from-blue-600 hover:to-indigo-700 transition-all">
                  <FileText size={20} />
                  Choose File
                </div>
                <p className="text-sm text-gray-400 mt-4">Supports PDF, DOCX, TXT files up to 10MB</p>
              </label>
            </div>
          </div>
          
          {file && (
            <div className="mt-6 p-6 bg-gradient-to-r from-blue-50 to-indigo-50 rounded-2xl border border-blue-200">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-4">
                  <div className="p-3 bg-blue-500 rounded-xl">
                    <FileText className="text-white" size={24} />
                  </div>
                  <div>
                    <p className="font-semibold text-gray-800 text-lg">{file.name}</p>
                    <p className="text-gray-600">{(file.size / 1024 / 1024).toFixed(2)} MB</p>
                  </div>
                </div>
                <button
                  onClick={analyzeDocument}
                  disabled={isAnalyzing}
                  className="px-8 py-3 bg-gradient-to-r from-green-500 to-emerald-600 hover:from-green-600 hover:to-emerald-700 disabled:from-gray-400 disabled:to-gray-500 text-white font-semibold rounded-xl transition-all shadow-lg hover:shadow-xl flex items-center gap-2"
                >
                  <Brain size={20} />
                  {isAnalyzing ? 'Analyzing...' : 'Analyze Document'}
                </button>
              </div>
            </div>
          )}
        </div>

        {/* Error */}
        {error && (
          <div className="mb-8 p-6 bg-red-50 border-l-4 border-red-500 rounded-xl">
            <div className="flex items-center gap-3">
              <AlertCircle className="text-red-500" size={24} />
              <p className="text-red-700 font-medium">{error}</p>
            </div>
          </div>
        )}

        {/* Loading */}
        {isAnalyzing && (
          <div className="mb-8 p-12 bg-white rounded-3xl shadow-xl border text-center">
            <div className="relative mb-6">
              <div className="animate-spin mx-auto w-16 h-16 border-4 border-blue-200 border-t-blue-600 rounded-full"></div>
              <Brain className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 text-blue-600" size={24} />
            </div>
            <h3 className="text-xl font-semibold text-gray-800 mb-2">AI is analyzing your document</h3>
            <p className="text-gray-600">This may take a few moments depending on document size</p>
          </div>
        )}

        {/* Results */}
        {analysis && (
          <div className="space-y-8">
            {/* Analysis Report */}
            <div className="bg-white rounded-3xl shadow-xl border p-8">
              <div className="flex items-center justify-between mb-6">
                <div className="flex items-center gap-3">
                  <div className="p-2 bg-green-100 rounded-xl">
                    <FileText className="text-green-600" size={24} />
                  </div>
                  <h3 className="text-2xl font-bold text-gray-800">Analysis Results</h3>
                </div>
                <button
                  onClick={downloadAnalysis}
                  className="px-6 py-3 bg-gradient-to-r from-green-500 to-emerald-600 hover:from-green-600 hover:to-emerald-700 text-white font-semibold rounded-xl transition-all shadow-lg hover:shadow-xl flex items-center gap-2"
                >
                  <Download size={18} />
                  Download Report
                </button>
              </div>
              
              <div className="bg-gradient-to-br from-gray-50 to-blue-50 rounded-2xl p-6 border">
                <div className="mb-4 pb-4 border-b border-gray-200">
                  <p className="text-sm text-gray-600">
                    <span className="font-medium">{analysis.fileName}</span> • 
                    <span className="font-medium">{analysis.fileType.toUpperCase()}</span> • 
                    <span>{analysis.timestamp.toLocaleString()}</span>
                  </p>
                </div>
                <div className="prose max-w-none">
                  <pre className="whitespace-pre-wrap text-sm text-gray-700 font-sans max-h-96 overflow-y-auto leading-relaxed">
                    {analysis.summary}
                  </pre>
                </div>
              </div>
            </div>

            {/* Chat Section */}
            <div className="bg-white rounded-3xl shadow-xl border p-8">
              <div className="flex items-center gap-3 mb-6">
                <div className="p-2 bg-blue-100 rounded-xl">
                  <MessageCircle className="text-blue-600" size={24} />
                </div>
                <h3 className="text-2xl font-bold text-gray-800">Ask Questions About Your Document</h3>
              </div>
              
              <div className="border-2 border-gray-200 rounded-2xl overflow-hidden">
                {/* Messages */}
                <div className="h-96 overflow-y-auto p-6 bg-gradient-to-b from-gray-50 to-white">
                  <div className="space-y-4">
                    {chatMessages.map((message) => (
                      <div key={message.id} className={`flex ${message.sender === 'user' ? 'justify-end' : 'justify-start'}`}>
                        <div className={`max-w-[75%] p-4 rounded-2xl shadow-sm ${
                          message.sender === 'user'
                            ? 'bg-gradient-to-r from-blue-500 to-indigo-600 text-white'
                            : 'bg-white border border-gray-200 text-gray-800'
                        }`}>
                          <div className="text-sm leading-relaxed whitespace-pre-wrap">{message.text}</div>
                          <div className={`text-xs mt-2 ${
                            message.sender === 'user' ? 'text-blue-100' : 'text-gray-500'
                          }`}>
                            {message.timestamp.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                          </div>
                        </div>
                      </div>
                    ))}
                    {isChatting && (
                      <div className="flex justify-start">
                        <div className="bg-white border border-gray-200 p-4 rounded-2xl shadow-sm">
                          <div className="flex space-x-2">
                            <div className="w-2 h-2 bg-blue-400 rounded-full animate-bounce"></div>
                            <div className="w-2 h-2 bg-blue-400 rounded-full animate-bounce" style={{ animationDelay: '0.1s' }}></div>
                            <div className="w-2 h-2 bg-blue-400 rounded-full animate-bounce" style={{ animationDelay: '0.2s' }}></div>
                          </div>
                        </div>
                      </div>
                    )}
                  </div>
                </div>

                {/* Input */}
                <div className="p-6 bg-white border-t-2 border-gray-200">
                  <div className="flex gap-4">
                    <textarea
                      value={chatInput}
                      onChange={(e) => setChatInput(e.target.value)}
                      onKeyPress={handleChatKeyPress}
                      placeholder="Ask anything about your document: 'What are the key terms?' or 'Explain clause 5'..."
                      className="flex-1 border-2 border-gray-200 rounded-xl px-4 py-3 text-sm resize-none focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                      rows="3"
                      disabled={isChatting}
                    />
                    <button
                      onClick={sendChatMessage}
                      disabled={!chatInput.trim() || isChatting}
                      className="px-6 py-3 bg-gradient-to-r from-blue-500 to-indigo-600 hover:from-blue-600 hover:to-indigo-700 disabled:from-gray-300 disabled:to-gray-400 text-white font-semibold rounded-xl transition-all shadow-lg hover:shadow-xl"
                    >
                      <Send size={20} />
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default DocumentAnalyzer;